{% extends 'base.html' %}

{% block title %} JavaScript {% endblock %}

{% block header %} promise chaining {% endblock %}

{% block content %}
<section>
  <pre>new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000); // (*)
}).then(function(result) { // (**)
  return result * 2;
}).then(function(result) { // (***)
  return result * 2;
}).then(function(result) {
  return result * 2;
});</pre>
  <pre>new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000);
}).then(function(result) {
  return new Promise((resolve, reject) => { // (*)
    setTimeout(() => resolve(result * 2), 1000);
  });
}).then(function(result) { // (**)
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });
}).then(function(result) {
  alert(result); // 4
});</pre>
</section>
<section>
  <h2>loadScript promise 사용</h2>
  <pre>loadScript("/article/promise-chaining/one.js")
  .then((script) => loadScript("/article/promise-chaining/two.js");
  ).then((script) => loadScript("/article/promise-chaining/three.js");
  ).then(function(script) {
    // 불러온 스크립트 안에 정의된 함수를 호출해 실제로 스크립트들이 정상적으로 로드되었는지 확인합니다.
    one();
    two();
    three();
  });</pre>
</section>
<section>
  <h2>fetch 사용</h2>
  <pre>fetch('/article/promise-chaining/user.json')
  .then(response => response.text())
  .then(text => alert(text)); // {"name": "Violet-Bora-Lee", "isAdmin": true}</pre>
    <pre>fetch('/article/promise-chaining/user.json')
  .then(response => response.json())
  .then(user => fetch(`https://api.github.com/users/${user.name}`))
  .then(response => response.json())
  .then(githubUser => new Promise(function(resolve, reject) { // (*)
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => {
      img.remove();
      resolve(githubUser); // (**)
    }, 3000);
  }))
  // 3초 후 동작함
  .then(githubUser => alert(`${githubUser.name}의 이미지를 성공적으로 출력하였습니다.`))
  .catch(error => alert(error.message));</pre>
    <pre>refactory fetch
function loadJson(url) {
  return fetch(url)
    .then(response => response.json());
}
function loadGithubUser(name) {
  return fetch(`https://api.github.com/users/${name}`)
    .then(response => response.json());
}
function showAvatar(githubUser) {
  return new Promise(function(resolve, reject) {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => {
      img.remove();
      resolve(githubUser);
    }, 3000);
  });
}
// 함수를 이용하여 다시 동일 작업 수행
loadJson('/article/promise-chaining/user.json')
  .then(user => loadGithubUser(user.name))
  .then(showAvatar)
  .then(githubUser => alert(`Finished showing ${githubUser.name}`))
  .catch(error => alert(error.message));
  // ...</pre>
</section>
<section>
  <h2>애러 처리</h2>
  <pre>new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {
  throw new Error("에러 발생!"); // 프라미스가 거부됨
}).catch(alert); // Error: 에러 발생!</pre>
    <pre>new Promise((resolve, reject) => {
  resolve("OK");
}).then((result) => {
  blabla(); // 존재하지 않는 함수
}).catch(alert); // ReferenceError: blabla is not defined</pre>
  <h2>처리되지 못한 거부</h2>
  <h3>자바스크립트 엔진은 프라미스 거부를 추적하다가 위와 같은 상황이 발생하면
    전역 에러를 생성합니다. 콘솔창을 열고 예시를 실행하면 전역 에러를 확인할 수 있습니다.</h3>
  <h3>브라우저 환경에선 이런 에러를 unhandledrejection 이벤트로 처리할 수 있습니다.</h3>
  <pre>window.addEventListener('unhandledrejection', function(event) {
  // unhandledrejection 이벤트엔 두 개의 특수 프로퍼티가 있습니다.
  alert(event.promise); // [object Promise] - 에러를 생성하는 프라미스
  alert(event.reason); // Error: 에러 발생! - 처리하지 못한 에러 객체
});

new Promise(function() {
  throw new Error("에러 발생!");
}); // 에러를 처리할 수 있는 .catch 핸들러가 없음</pre>
</section>
{% endblock content %}